<a href="https://colab.research.google.com/github/SMTorg/smt/blob/master/tutorial/SMT_DesignSpace_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div class="jumbotron text-left"><b>
    
This tutorial describes how to use de DesignSpace within the SMT toolbox. 
<div>
    
    July 2024 - `SMT version 2.6.3`
  
     Paul Saves, Jasper Bussemaker (DLR), and Nathalie BARTOLI (ONERA/DTIS/M2CI)

<div class="alert alert-info fade in" id="d110">
<p>Some updates</p>
<ol> -  Manipulation of mixed DOE (continuous, integer,  categorical and hierarchical variables) </ol>
</div>

<p class="alert alert-success" style="padding:1em">
To use SMT models, please follow this link : https://github.com/SMTorg/SMT/blob/master/README.md. The documentation is available here: http://smt.readthedocs.io/en/latest/
</p>

The reference paper is available 
here https://www.sciencedirect.com/science/article/pii/S0965997818309360?via%3Dihub 

or as a preprint: http://mdolab.engin.umich.edu/content/python-surrogate-modeling-framework-derivatives

For mixed integer with continuous relaxation, the reference paper is available here https://www.sciencedirect.com/science/article/pii/S0925231219315619

In [1]:
!pip install configspace==0.6.1
#!pip install adsg_core --pre
#!pip install adsg-core[nb]

#to install smt
!pip install smt

!pip install git+https://github.com/jbussemaker/adsg-core.git@dev

#to have the latest version
!pip install smt --pre

  Cloning https://github.com/jbussemaker/adsg-core.git (to revision dev) to /tmp/pip-req-build-zdih3k_0
  Running command git clone --filter=blob:none --quiet https://github.com/jbussemaker/adsg-core.git /tmp/pip-req-build-zdih3k_0
  Running command git checkout -b dev --track origin/dev
  Switched to a new branch 'dev'
  Branch 'dev' set up to track remote branch 'dev' from 'origin'.
  Resolved https://github.com/jbussemaker/adsg-core.git to commit be22d7db9cfb0dafc125cc87ec3b86228886d5f9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


<div class="alert alert-warning" >
If you use hierarchical variables and the size of your doe greater than 30 points, you may leverage the `numba` JIT compiler to speed up the computation
To do so:
    
 - install numba library
    
     `pip install numba`
    
    
 - and define the environment variable `USE_NUMBA_JIT = 1` (unset or 0 if you do not want to use numba) 
    
     - Linux: export USE_NUMBA_JIT = 1
    
     - Windows: set USE_NUMBA_JIT = 1

</div>

In [2]:
#to ignore warning messages
import warnings
warnings.filterwarnings("ignore")

import os
import unittest
import numpy as np
from sys import argv
import matplotlib.pyplot as plt
import time
%matplotlib inline

from smt.applications import EGO
from smt.applications.ego import Evaluator
from smt.utils.sm_test_case import SMTestCase
from smt.problems import Branin, Rosenbrock, HierarchicalGoldstein
from smt.sampling_methods import FullFactorial
from multiprocessing import Pool
from smt.sampling_methods import LHS
import itertools
from smt.surrogate_models import (
    KRG,
    GEKPLS,
    KPLS,
    QP,
    MixIntKernelType,
    MixHrcKernelType,
)
from smt.applications.mixed_integer import (
    MixedIntegerContext,
    MixedIntegerSamplingMethod,
    MixedIntegerKrigingModel
)

from smt.utils.design_space import (
    DesignSpace,
    FloatVariable,
    IntegerVariable,
    OrdinalVariable,
    CategoricalVariable,
)

import plotly.io as pio
pio.renderers.default='notebook'


# Manipulate DOE with mixed, categorical & hierarchical variables

4 variables 
 - 1 categorical variable with 2 labels ['A', 'B'] # x0 categorical: A or B; order is not relevant
 - 1 ordinal variable with 3 levels ['C', 'D', 'E']),  # x1 ordinal: C, D or E; order is relevant
 - 1 integer variable [0,2]: 3 possibilities: 0, 1, 2
 - 1 continuous variable $\in [0, 1]$
 
 
 **Posssibility to have hierarchical variable: x1 exists only if x0 = 'A'**

In [3]:
#Instantiate the design space with all its design variables:

ds = DesignSpace([
    CategoricalVariable(['A', 'B']),  # x0 categorical: A or B; order is not relevant
    OrdinalVariable(['C', 'D', 'E']),  # x1 ordinal: C, D or E; order is relevant
    IntegerVariable(0, 2),  # x2 integer between 0 and 2 (inclusive): 0, 1, 2
    FloatVariable(0, 1),  # c3 continuous between 0 and 1
    ])

print("Number of design variables",len(ds.design_variables))
#You can define decreed variables (conditional activation):
ds.declare_decreed_var(decreed_var=1, meta_var=0, meta_value='A')  # Activate x1 if x0 == A

Number of design variables 4


In [4]:
## To give some examples
#It is also possible to randomly sample design vectors conforming to the constraints:
n = 5
x_sampled, is_acting_sampled = ds.sample_valid_x(5)

print('Data encoded: \n', x_sampled)
print('Data in initial space: \n', ds.decode_values(x_sampled))

Data encoded: 
 [[ 0.          0.          1.          0.41582327]
 [ 1.          0.         -0.          0.16624317]
 [ 0.          0.          2.          0.55282681]
 [ 1.          0.          1.          0.36303208]
 [ 1.          0.          1.          0.07135995]]
Data in initial space: 
 [['A', 'C', 1.0, 0.41582327100213723], ['B', 'C', -0.0, 0.16624317060315286], ['A', 'C', 2.0, 0.5528268144302348], ['B', 'C', 1.0, 0.3630320794879359], ['B', 'C', 1.0, 0.07135995107938786]]


In [5]:
#After defining everything correctly, you can then use the design space object 
#to correct design vectors and get information about which design variables are acting:
x_corr, is_acting = ds.correct_get_acting(x_sampled) 
print("Which variables are active \n", is_acting)

Which variables are active 
 [[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]
 [ True False  True  True]
 [ True False  True  True]]


In [6]:
#If needed, it is possible to get the legacy design space definition format:
xlimits = ds.get_x_limits()
cont_bounds = ds.get_num_bounds()
unfolded_cont_bounds = ds.get_unfolded_num_bounds()
print("Limits of each variable \n", xlimits)
print("Continuous bounds with the encoding done (4 variables now) \n", cont_bounds)
print("Continuous bounds with the unfolded encoding done (5 variables now)\n", unfolded_cont_bounds)

Limits of each variable 
 [['A', 'B'], ['0', '1', '2'], (0, 2), (0, 1)]
Continuous bounds with the encoding done (4 variables now) 
 [[0 1]
 [0 2]
 [0 2]
 [0 1]]
Continuous bounds with the unfolded encoding done (5 variables now)
 [[0. 1.]
 [0. 1.]
 [0. 2.]
 [0. 2.]
 [0. 1.]]


# Manipulate DOE with continuous variables

In [7]:
#You can also instantiate a purely-continuous design space from bounds directly:
continuous_design_space = DesignSpace([(0, 1), (0, 2), (.5, 5.5)])
print("Number of design variables =",continuous_design_space.n_dv, ' or ', len(continuous_design_space.design_variables))

Number of design variables = 3  or  3


In [8]:
x_sampled_cont, is_acting_sampled_cont = continuous_design_space.sample_valid_x(5)

In [9]:
print('Data encoded: \n', x_sampled_cont)
print('Is_acting: \n', is_acting_sampled_cont)

Data encoded: 
 [[3.75624156e-01 1.93362861e+00 4.16202680e+00]
 [1.56591655e-03 1.86131643e+00 2.40796294e+00]
 [8.51254118e-01 1.10599374e+00 1.17656540e+00]
 [8.64306279e-01 9.57233142e-01 2.25440518e+00]
 [6.43514074e-02 5.73824730e-01 3.81959584e+00]]
Is_acting: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Moving towards Architecture Design Space Graph (ADSG)

In [21]:
from adsg_core import BasicADSG, NamedNode, SelectionChoiceNode,DesignVariableNode

# Create the ADSG
adsg = BasicADSG()

ndv=13


# Create nodes
n = [NamedNode(f'N{i}') for i in range(ndv)]
n = [NamedNode("MLP"),NamedNode("Learning_rate"), NamedNode("Activation_function"),
     NamedNode("Optimizer"),NamedNode("Decay"),NamedNode("Power_update"), NamedNode("Average_start"),
     NamedNode("Running_Average_1"),NamedNode("Running_Average_2"),NamedNode("Numerical_Stability"),
     NamedNode("Nb_layers"), NamedNode("Layer_1"), NamedNode("Layer_2"), NamedNode("Layer_3"), # NamedNode("Dropout"),
     NamedNode("ASGD"),NamedNode("Adam"), NamedNode("20...40"),NamedNode("40"),NamedNode("45"),NamedNode("20...40"), NamedNode("40"),NamedNode("45"), NamedNode("20...40"),NamedNode("40"),NamedNode("45")]
adsg.add_node(n[1])
adsg.add_node(n[2])
#adsg.add_node(n[3])

# Add some edges
adsg.add_edges([
 # (n[0], n[1]),
 # (n[0], n[2]),
 # (n[0], n[3]),
  (n[3],n[10]),
  (n[14],n[4]),
  (n[14],n[5]),
  (n[14],n[6]),
  (n[15],n[7]),
  (n[15],n[8]),
  (n[15],n[9]),
])

choiceo=adsg.add_selection_choice("Optimizer_Choice", n[3], [n[14], n[15]])


choicenl=adsg.add_selection_choice("#layers", n[10], [n[11], n[12],n[13]])
adsg.add_edges([ (n[12],n[11]), (n[13],n[12]) ])
a = []
for i in range(3) :
  a.append(NamedNode(str(25+5*i)))
b = a.copy()
b.append(n[17])
b.append(n[18])
choicel1=adsg.add_selection_choice("#neurons", n[11], b)


a = []
for i in range(3) :
  a.append(NamedNode(str(25+5*i)))
b = a.copy()
b.append(n[20])
b.append(n[21])
choicel1=adsg.add_selection_choice("#neurons", n[12], b)

a = []
for i in range(3) :
  a.append(NamedNode(str(25+5*i)))
b = a.copy()
b.append(n[23])
b.append(n[24])
choicel1=adsg.add_selection_choice("#neurons", n[13], b)

#adsg.add_edges([ (n[18],n[17]), (n[17],n[16]) ])
#adsg.add_edges([ (n[21],n[20]), (n[20],n[19]) ])
#adsg.add_edges([ (n[24],n[23]), (n[23],n[22]) ])

adsg.add_incompatibility_constraint([n[15], n[13]])
adsg.add_incompatibility_constraint([n[14], n[17]])
adsg.add_incompatibility_constraint([n[14], n[18]])
adsg.add_incompatibility_constraint([n[14], n[20]])
adsg.add_incompatibility_constraint([n[14], n[21]])
adsg.add_incompatibility_constraint([n[14], n[23]])
adsg.add_incompatibility_constraint([n[14], n[24]])
start_nodes = set()
start_nodes.add(n[3])
start_nodes.add(n[2])
start_nodes.add(n[1])
#start_nodes.add(n[0])



adsg.add_edges([
    (n[1], DesignVariableNode('x0', bounds=(0, 1))),
 (n[4], DesignVariableNode('x1', bounds=(0, 1))),
 (n[5], DesignVariableNode('x2', bounds=(0, 1))),
 (n[6], DesignVariableNode('x3', bounds=(0, 1))),
 (n[7], DesignVariableNode('x4', bounds=(0, 1))),
 (n[8], DesignVariableNode('x5', bounds=(0, 1))),
# (n[9], DesignVariableNode('x6', bounds=(0, 1))),
 (n[9], DesignVariableNode('x6', options=["0", "1"])),

 #(n[11], DesignVariableNode('x7', options=("0", "1"))),

])

choiceo=adsg.add_selection_choice("Activation_Choice", n[2], [NamedNode("ReLU"), NamedNode("Sigmoid"),NamedNode("Tanh")])

adsg = adsg.set_start_nodes(start_nodes)

adsg.render()

plt.show() 

In [22]:
from adsg_core import GraphProcessor
gp = GraphProcessor(adsg)

print('Design variables:', gp.des_vars[0:5])
print(str(gp.des_vars[5:])[1:])
print('Objectives:', gp.objectives)
print('Constraints:', gp.constraints)

# Display some details about the encoders used for
# formulating the optimization problem
gp.get_statistics()



Design variables: [DV: #layers [3 opts], DV: Activation_Choice [3 opts], DV: Optimizer_Choice [2 opts], DV: #neurons [5 opts], DV: #neurons_2 [5 opts]]
DV: #neurons_3 [5 opts], DV: x0 [0.00..1.00], DV: x1 [0.00..1.00], DV: x2 [0.00..1.00], DV: x3 [0.00..1.00], DV: x4 [0.00..1.00], DV: x5 [0.00..1.00], DV: x6 [2 opts]]
Objectives: []
Constraints: []


n_valid  n_declared  n_discrete  n_dim_cont  \
type                                                                
option-decisions          207        1350           6           0   
additional-dvs            297           2           1           6   
total-design-space        297        4500           7           6   
total-design-problem      297        4500           7           6   

                      n_dim_cont_mean  n_exist  imp_ratio  imp_ratio_comb  \
type                                                                        
option-decisions             0.000000        1   6.521739        6.521739   
additional-dvs               3.565217      207   2.345898        1.393939   
total-design-space           3.565217        1  25.498891       15.151515   
total-design-problem         3.565217        1  25.498891       15.151515   

                      imp_ratio_cont   inf_idx  dist_corr   encoder  
type                                                                 
option-decisions            1.000000  0.531986        0.0  complete  
additional-dvs              1.682927  1.000000        0.0            
total-design-space          1.682927  0.538807        0.0  complete  
total-design-problem        1.682927  0.538807        0.0  complete

In [23]:
# Define the mixed hierarchical design space

from adsg_core import GraphProcessor
gp = GraphProcessor(adsg)
listvar= []
gvars= gp._all_des_var_data[0]

for i in gvars :
    print(i._bounds,i.n_opts,type(i.node),i.name)
    if i._bounds is not None : 
        listvar.append(FloatVariable(lower=i._bounds[0],upper=i._bounds[1]) )
    elif type(i.node) is SelectionChoiceNode:
        a=((str(i._opts).replace("[", "").replace("]", "").replace(" ", "").replace("'", "").split(',')))
        listvar.append(CategoricalVariable(a) )
    else : 
        a=((str(i._opts).replace("[", "").replace("]", "").replace(" ", "").replace("'", "").split(',')))
        listvar.append(OrdinalVariable(a) )

design_space = DesignSpace(listvar)

None 3 <class 'adsg_core.graph.adsg_nodes.SelectionChoiceNode'> #layers
None 3 <class 'adsg_core.graph.adsg_nodes.SelectionChoiceNode'> Activation_Choice
None 2 <class 'adsg_core.graph.adsg_nodes.SelectionChoiceNode'> Optimizer_Choice
None 5 <class 'adsg_core.graph.adsg_nodes.SelectionChoiceNode'> #neurons
None 5 <class 'adsg_core.graph.adsg_nodes.SelectionChoiceNode'> #neurons_2
None 5 <class 'adsg_core.graph.adsg_nodes.SelectionChoiceNode'> #neurons_3
(0, 1) None <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x0
(0, 1) None <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x1
(0, 1) None <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x2
(0, 1) None <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x3
(0, 1) None <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x4
(0, 1) None <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x5
None 2 <class 'adsg_core.graph.adsg_nodes.DesignVariableNode'> x6


In [24]:
print(design_space)

Design space:
x0: Cat ['Layer_1', 'Layer_2', 'Layer_3']
x1: Cat ['ReLU', 'Sigmoid', 'Tanh']
x2: Cat ['ASGD', 'Adam']
x3: Cat ['25', '30', '35', '40', '45']
x4: Cat ['25', '30', '35', '40', '45']
x5: Cat ['25', '30', '35', '40', '45']
x6: Float (0, 1)
x7: Float (0, 1)
x8: Float (0, 1)
x9: Float (0, 1)
x10: Float (0, 1)
x11: Float (0, 1)
x12: Ord ['0', '1']


In [45]:
print(gp.dv_is_conditionally_active)

[False, False, False, True, True, True, False, True, True, True, True, True, True]


In [60]:
a = [i for i, x in enumerate(gp.dv_is_conditionally_active) if x]
nodelist = list(adsg._graph.nodes)
c = str(list(adsg._graph.nodes))[1:-1].replace("D[Sel:","[").replace("DV[","[").replace(" ","").split(",") 
cleaned_c = [element.strip()[1:-1] for element in c if element.strip().startswith('[') and element.strip().endswith(']')]
print(cleaned_c)
for i in range(np.sum(gp.dv_is_conditionally_active)) :
    print(a[i])
    print(gvars[a[i]].name)


['Learning_rate', 'Activation_function', 'Optimizer', 'Nb_layers', 'ASGD', 'Decay', 'Power_update', 'Average_start', 'Adam', 'Running_Average_1', 'Running_Average_2', 'Numerical_Stability', 'Optimizer_Choice', '#layers', 'Layer_1', 'Layer_2', 'Layer_3', '#neurons', '25', '30', '35', '40', '45', '#neurons', '25', '30', '35', '40', '45', '#neurons', '25', '30', '35', '40', '45', 'x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'Activation_Choice', 'ReLU', 'Sigmoid', 'Tanh']
3
#neurons
4
#neurons_2
5
#neurons_3
7
x1
8
x2
9
x3
10
x4
11
x5
12
x6


In [30]:
design_space.declare_decreed_var(decreed_var =10, meta_var =9, meta_value =[1,2,3])
design_space.declare_decreed_var(decreed_var =11, meta_var =9, meta_value =[2,3])
design_space.declare_decreed_var(decreed_var =12, meta_var =9, meta_value =3)

In [28]:
# Define the mixed hierarchical design space
design_space = DesignSpace ([
    FloatVariable (0, 1), #Learning rate
    CategoricalVariable (["ReLU","Sigmoid","Tanh"]), #3 possible choices for the activation function
    CategoricalVariable (["ASGD","Adam"]), #2 possible choices for the optimizer

    FloatVariable (0, 1), #ASGD Decay
    FloatVariable (0, 1), #ASGD Power update
    FloatVariable (0, 1), #ASGD Average start

    FloatVariable (0, 1), #Adam Running Average 1
    FloatVariable (0, 1), #Adam Running Average 2
    FloatVariable (0, 1), #Adam Numerical Stability

    IntegerVariable (1, 3), #for the number of hidden layers  (l=x9)
    OrdinalVariable (['25','30','35','40','45']), #number of hidden neurons layer 1
    OrdinalVariable (['25','30','35','40','45']), #number of hidden neurons layer 2
    OrdinalVariable (['25','30','35','40','45']), #number of hidden neurons layer 3
])

#ASGD vs Adam optimizer options activated or deactivated
design_space.declare_decreed_var(decreed_var =3, meta_var =2, meta_value =["ASGD"])
design_space.declare_decreed_var(decreed_var =4, meta_var =2, meta_value =["ASGD"])
design_space.declare_decreed_var(decreed_var =5, meta_var =2, meta_value =["ASGD"])
design_space.declare_decreed_var(decreed_var =6, meta_var =2, meta_value =["Adam"])
design_space.declare_decreed_var(decreed_var =7, meta_var =2, meta_value =["Adam"])
design_space.declare_decreed_var(decreed_var =8, meta_var =2, meta_value =["Adam"])

# Number of hidden layers: Activate x11 when x9 in [2, 3] and x12 when x9 == 3
design_space.add_value_constraint(var1=9, value1=3, var2=2, value2=["Adam"])  # Forbid 3  hidden layers with Adam
design_space.declare_decreed_var(decreed_var =10, meta_var =9, meta_value =[1,2,3])
design_space.declare_decreed_var(decreed_var =11, meta_var =9, meta_value =[2,3])
design_space.declare_decreed_var(decreed_var =12, meta_var =9, meta_value =3)
design_space.add_value_constraint(var1=10, value1=['40','45'], var2=2, value2=["ASGD"])  # Forbid more than 35 neurons with ASGD
design_space.add_value_constraint(var1=11, value1=['40','45'], var2=2, value2=["ASGD"])  # Forbid more than 35 neurons with ASGD
design_space.add_value_constraint(var1=12, value1=['40','45'], var2=2, value2=["ASGD"])  # Forbid more than 35 neurons with ASGD

