<a href="https://colab.research.google.com/github/SMTorg/smt/blob/master/tutorial/SMT_DesignSpace_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div class="jumbotron text-left"><b>
    
This tutorial describes how to use de DesignSpace within the SMT toolbox. 
<div>
    
    July 2024 - `SMT version 2.6.3`
  
     Paul Saves, Jasper Bussemaker (DLR), and Nathalie BARTOLI (ONERA/DTIS/M2CI)

<div class="alert alert-info fade in" id="d110">
<p>Some updates</p>
<ol> -  Manipulation of mixed DOE (continuous, integer,  categorical and hierarchical variables) </ol>
</div>

<p class="alert alert-success" style="padding:1em">
To use SMT models, please follow this link : https://github.com/SMTorg/SMT/blob/master/README.md. The documentation is available here: http://smt.readthedocs.io/en/latest/
</p>

The reference paper is available 
here https://www.sciencedirect.com/science/article/pii/S0965997818309360?via%3Dihub 

or as a preprint: http://mdolab.engin.umich.edu/content/python-surrogate-modeling-framework-derivatives

For mixed integer with continuous relaxation, the reference paper is available here https://www.sciencedirect.com/science/article/pii/S0925231219315619

In [1]:
!pip install configspace==0.6.1
#!pip install adsg_core --pre
#!pip install adsg-core[nb]

#to install smt
!pip install smt

!pip install git+https://github.com/jbussemaker/adsg-core.git@dev

#to have the latest version
!pip install smt --pre

  Cloning https://github.com/jbussemaker/adsg-core.git (to revision dev) to /tmp/pip-req-build-qsmkmsaa
  Running command git clone --filter=blob:none --quiet https://github.com/jbussemaker/adsg-core.git /tmp/pip-req-build-qsmkmsaa
  Running command git checkout -b dev --track origin/dev
  Switched to a new branch 'dev'
  Branch 'dev' set up to track remote branch 'dev' from 'origin'.
  Resolved https://github.com/jbussemaker/adsg-core.git to commit be22d7db9cfb0dafc125cc87ec3b86228886d5f9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


<div class="alert alert-warning" >
If you use hierarchical variables and the size of your doe greater than 30 points, you may leverage the `numba` JIT compiler to speed up the computation
To do so:
    
 - install numba library
    
     `pip install numba`
    
    
 - and define the environment variable `USE_NUMBA_JIT = 1` (unset or 0 if you do not want to use numba) 
    
     - Linux: export USE_NUMBA_JIT = 1
    
     - Windows: set USE_NUMBA_JIT = 1

</div>

In [2]:
#to ignore warning messages
import warnings
warnings.filterwarnings("ignore")

import os
import unittest
import numpy as np
from sys import argv
import matplotlib.pyplot as plt
import time
%matplotlib inline

from smt.applications import EGO
from smt.applications.ego import Evaluator
from smt.utils.sm_test_case import SMTestCase
from smt.problems import Branin, Rosenbrock, HierarchicalGoldstein
from smt.sampling_methods import FullFactorial
from multiprocessing import Pool
from smt.sampling_methods import LHS
import itertools
from smt.surrogate_models import (
    KRG,
    GEKPLS,
    KPLS,
    QP,
    MixIntKernelType,
    MixHrcKernelType,
)
from smt.applications.mixed_integer import (
    MixedIntegerContext,
    MixedIntegerSamplingMethod,
    MixedIntegerKrigingModel
)

from smt.utils.design_space import (
    DesignSpace,
    FloatVariable,
    IntegerVariable,
    OrdinalVariable,
    CategoricalVariable,
)

import plotly.io as pio
pio.renderers.default='notebook'


# Manipulate DOE with mixed, categorical & hierarchical variables

4 variables 
 - 1 categorical variable with 2 labels ['A', 'B'] # x0 categorical: A or B; order is not relevant
 - 1 ordinal variable with 3 levels ['C', 'D', 'E']),  # x1 ordinal: C, D or E; order is relevant
 - 1 integer variable [0,2]: 3 possibilities: 0, 1, 2
 - 1 continuous variable $\in [0, 1]$
 
 
 **Posssibility to have hierarchical variable: x1 exists only if x0 = 'A'**

In [3]:
#Instantiate the design space with all its design variables:

ds = DesignSpace([
    CategoricalVariable(['A', 'B']),  # x0 categorical: A or B; order is not relevant
    OrdinalVariable(['C', 'D', 'E']),  # x1 ordinal: C, D or E; order is relevant
    IntegerVariable(0, 2),  # x2 integer between 0 and 2 (inclusive): 0, 1, 2
    FloatVariable(0, 1),  # c3 continuous between 0 and 1
    ])

print("Number of design variables",len(ds.design_variables))
#You can define decreed variables (conditional activation):
ds.declare_decreed_var(decreed_var=1, meta_var=0, meta_value='A')  # Activate x1 if x0 == A

Number of design variables 4


In [4]:
## To give some examples
#It is also possible to randomly sample design vectors conforming to the constraints:
n = 5
x_sampled, is_acting_sampled = ds.sample_valid_x(5)

print('Data encoded: \n', x_sampled)
print('Data in initial space: \n', ds.decode_values(x_sampled))

Data encoded: 
 [[ 0.          2.         -0.          0.2080406 ]
 [ 0.          0.          1.          0.68792902]
 [ 0.          2.          1.          0.32768399]
 [ 0.          1.         -0.          0.67460808]
 [ 0.          0.         -0.          0.08387924]]
Data in initial space: 
 [['A', 'E', -0.0, 0.20804060028495952], ['A', 'C', 1.0, 0.6879290240972027], ['A', 'E', 1.0, 0.32768399075187604], ['A', 'D', -0.0, 0.6746080768493098], ['A', 'C', -0.0, 0.08387924339852171]]


In [5]:
#After defining everything correctly, you can then use the design space object 
#to correct design vectors and get information about which design variables are acting:
x_corr, is_acting = ds.correct_get_acting(x_sampled) 
print("Which variables are active \n", is_acting)

Which variables are active 
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [6]:
#If needed, it is possible to get the legacy design space definition format:
xlimits = ds.get_x_limits()
cont_bounds = ds.get_num_bounds()
unfolded_cont_bounds = ds.get_unfolded_num_bounds()
print("Limits of each variable \n", xlimits)
print("Continuous bounds with the encoding done (4 variables now) \n", cont_bounds)
print("Continuous bounds with the unfolded encoding done (5 variables now)\n", unfolded_cont_bounds)

Limits of each variable 
 [['A', 'B'], ['0', '1', '2'], (0, 2), (0, 1)]
Continuous bounds with the encoding done (4 variables now) 
 [[0 1]
 [0 2]
 [0 2]
 [0 1]]
Continuous bounds with the unfolded encoding done (5 variables now)
 [[0. 1.]
 [0. 1.]
 [0. 2.]
 [0. 2.]
 [0. 1.]]


# Manipulate DOE with continuous variables

In [7]:
#You can also instantiate a purely-continuous design space from bounds directly:
continuous_design_space = DesignSpace([(0, 1), (0, 2), (.5, 5.5)])
print("Number of design variables =",continuous_design_space.n_dv, ' or ', len(continuous_design_space.design_variables))

Number of design variables = 3  or  3


In [8]:
x_sampled_cont, is_acting_sampled_cont = continuous_design_space.sample_valid_x(5)

In [9]:
print('Data encoded: \n', x_sampled_cont)
print('Is_acting: \n', is_acting_sampled_cont)

Data encoded: 
 [[0.6211392  0.99609568 3.79829878]
 [0.70086578 1.5552522  0.77369391]
 [0.74386417 0.43386098 1.77447691]
 [0.56025309 0.11930465 1.25259765]
 [0.23214073 1.88632861 1.48669667]]
Is_acting: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Moving towards Architecture Design Space Graph (ADSG)

In [10]:
from adsg_core import BasicADSG, NamedNode, SelectionChoiceNode,DesignVariableNode

# Create the ADSG
adsg = BasicADSG()

ndv=14


# Create nodes
n = [NamedNode(f'N{i}') for i in range(ndv)]
n = [NamedNode("MLP"),NamedNode("Learning rate"), NamedNode("Activation function"),
     NamedNode("Optimizer"),NamedNode("Decay"),NamedNode("Power update"), NamedNode("Average start"),
     NamedNode("Running Average 1"),NamedNode("Running Average 2"),NamedNode("Numerical Stability"),
     NamedNode("Nb. layers"), NamedNode("Layer 1"), NamedNode("Layer 2"), NamedNode("Layer 3"), # NamedNode("Dropout"),
     NamedNode("ASGD"),NamedNode("Adam"), NamedNode("20...40"),NamedNode("40"),NamedNode("45"),NamedNode("20...40"), NamedNode("40"),NamedNode("45"), NamedNode("20...40"),NamedNode("40"),NamedNode("45")]
adsg.add_node(n[1])
adsg.add_node(n[2])
#adsg.add_node(n[3])

# Add some edges
adsg.add_edges([
 # (n[0], n[1]),
 # (n[0], n[2]),
 # (n[0], n[3]),
  (n[3],n[10]),
  (n[14],n[4]),
  (n[14],n[5]),
  (n[14],n[6]),
  (n[15],n[7]),
  (n[15],n[8]),
  (n[15],n[9]),
])

choiceo=adsg.add_selection_choice("Optimizer_Choice", n[3], [n[14], n[15]])


choicenl=adsg.add_selection_choice("#layers", n[10], [n[11], n[12],n[13]])
adsg.add_edges([ (n[12],n[11]), (n[13],n[12]) ])
a = []
for i in range(3) :
  a.append(NamedNode(str(25+5*i)))
b = a.copy()
b.append(n[17])
b.append(n[18])
choicel1=adsg.add_selection_choice("#neurons", n[11], b)


a = []
for i in range(3) :
  a.append(NamedNode(str(25+5*i)))
b = a.copy()
b.append(n[20])
b.append(n[21])
choicel1=adsg.add_selection_choice("#neurons", n[12], b)

a = []
for i in range(3) :
  a.append(NamedNode(str(25+5*i)))
b = a.copy()
b.append(n[23])
b.append(n[24])
choicel1=adsg.add_selection_choice("#neurons", n[13], b)

#adsg.add_edges([ (n[18],n[17]), (n[17],n[16]) ])
#adsg.add_edges([ (n[21],n[20]), (n[20],n[19]) ])
#adsg.add_edges([ (n[24],n[23]), (n[23],n[22]) ])

adsg.add_incompatibility_constraint([n[15], n[13]])
adsg.add_incompatibility_constraint([n[14], n[17]])
adsg.add_incompatibility_constraint([n[14], n[18]])
adsg.add_incompatibility_constraint([n[14], n[20]])
adsg.add_incompatibility_constraint([n[14], n[21]])
adsg.add_incompatibility_constraint([n[14], n[23]])
adsg.add_incompatibility_constraint([n[14], n[24]])
start_nodes = set()
start_nodes.add(n[3])
start_nodes.add(n[2])
start_nodes.add(n[1])
#start_nodes.add(n[0])



adsg.add_edges([
    (n[1], DesignVariableNode('x0', bounds=(0, 1))),
 (n[4], DesignVariableNode('x1', bounds=(0, 1))),
 (n[5], DesignVariableNode('x2', bounds=(0, 1))),
 (n[6], DesignVariableNode('x3', bounds=(0, 1))),
 (n[7], DesignVariableNode('x4', bounds=(0, 1))),
 (n[8], DesignVariableNode('x5', bounds=(0, 1))),
 (n[9], DesignVariableNode('x6', bounds=(0, 1))),
 #(n[11], DesignVariableNode('x7', options=("0", "1"))),

])

choiceo=adsg.add_selection_choice("Activation_Choice", n[2], [NamedNode("ReLU"), NamedNode("Sigmoid"),NamedNode("Tanh")])

adsg = adsg.set_start_nodes(start_nodes)

adsg.render()

